on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0
        with:
          version: v0.4.1
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build, tag, and push
        run: |
          IMAGE_VERSION=$(cat VERSION)
          SHORT_SHA1=$(git rev-parse --short HEAD)
          PLATFORMS=$(cat PLATFORMS)
          echo "Building and pushing version ${IMAGE_VERSION} of image ${IMAGE_NAME}"
          docker buildx build --platform "${PLATFORMS}" --cache-from="type=registry,ref=${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}" --cache-to="type=registry,ref=${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1},mode=max" -t "${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}" --push .
        env:
          IMAGE_NAME: quay.io/eclipse/che-sidecar-vale
